### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by basudev1234** [truecaller/flutter-sdk#19]
Please upgrade the SDK to sound null safetey, to run the application we have to explicitely run the command --no-sound-null-safety

**Comment by parth0907** [comment]
Hi @basudev1234, 

Thanks for writing in! 

The process to upgrade the Truecaller Flutter SDK to support sound null safety is currently under evaluation. We will keep you updated regarding its progress.

In case of any further questions, please feel free to reach us via our support channel https://developer.truecaller.com/support for a faster and dedicated response.

Regards,
Parth

**Comment by shivangguptaa** [comment]
This issue is closed by #22 . Until the PR is resolved, you can use this. @parth0907 

```
truecaller_sdk:
    git:
      url: https://github.com/shivangguptaa/flutter-sdk
      ref: 6748859880aff3e76513d881b303955552b5bdb6
```
